//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumFotograficos
    {
        public int idFotografia { get; set; }
        public string nombreArchivo { get; set; }
        public string formato { get; set; }
        public string rutaGuardado { get; set; }
        public int idAlojamiento { get; set; }
    
        public virtual Alojamientos Alojamientos { get; set; }
    }
}
