//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlquilersAlojamientos
    {
        public int numeroContrato { get; set; }
        public int numeroMeses { get; set; }
        public decimal pagoMensual { get; set; }
        public DateTime fechaAlquiler { get; set; }
        public int idAlojamiento { get; set; }
    
        public virtual Alojamientos Alojamientos { get; set; }
    }
}
