//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public Calificaciones()
        {
            this.CalificacionesAlojamiento = new HashSet<CalificacionesAlojamiento>();
            this.CalificacionesArrendatario = new HashSet<CalificacionesArrendatario>();
        }
    
        public int idCalificacion { get; set; }
        public string comentarioAlojamiento { get; set; }
        public Nullable<int> calificacionAlojamiento { get; set; }
    
        public virtual ICollection<CalificacionesAlojamiento> CalificacionesAlojamiento { get; set; }
        public virtual ICollection<CalificacionesArrendatario> CalificacionesArrendatario { get; set; }
    }
}
