//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.CuentasBancarias = new HashSet<CuentasBancarias>();
            this.CuentasUsuarios = new HashSet<CuentasUsuarios>();
        }
    
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string nacionalidad { get; set; }
        public string genero { get; set; }
    
        public virtual Arrendadores Arrendadores { get; set; }
        public virtual Arrendatarios Arrendatarios { get; set; }
        public virtual ICollection<CuentasBancarias> CuentasBancarias { get; set; }
        public virtual ICollection<CuentasUsuarios> CuentasUsuarios { get; set; }
    }
}
